name: getseto_kyc_example
description: Minimal example app demonstrating GetSetO KYC SDK integration.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  getseto_sdk:
    git:
      url: https://github.com/getseto-com/getseto-sdk.git
      ref: v1.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpg
